### PR TITLE
added biicode support

### PR DESCRIPTION
**Pull request by MariadeAnton**
Hi skystrife,

I just added [biicode](https://www.biicode.com/) support for your library and explained basics in the readme , it's a biicode.conf file and some unobtrusive changes in CMakeLists.txt

To try it out with biicode (once installed):

```
 $ git clone https://github.com/MariadeAnton/cpptoml
 $ cd cpptoml
 $ bii init -L
 $ bii build
```
I've published **cpptoml** in biicode [amalulla/cpptoml](https://www.biicode.com/amalulla/cpptoml), but would be great if you could register keep it up-to-date in biicode. 

Hope you like this,

Maria

### CODE REVIEW

**Comment by skystrife** [comment]
Thank you! I cherry picked the top commit here (as  bebc235) since I applied my own travis-ci fixes before merging.

With any luck, this should be set up to auto-update the biicode block under skystrife/cpptoml now, whenever the travis build succeeds.

(Wish there was a way to mark this as "manually merged" or something...)

**Comment by MariadeAnton** [comment]
Don't worry - I definitely get that :) 

I'll delete my block asap - do you know there's a ```bii publish -r```option to link your repo to your biicode block? Let me know if you need a hand on this or your deploy to biicode.

**Comment by skystrife** [comment]
Oh, cool. I think I've done that now?

Working on trying to automate this so that it happens with every push to `master`.

**Comment by MariadeAnton** [comment]
You actually did, cool! It looks better now - I would also edit your block's description and tags from the block's page in biicode, it looks neater.

There are tons of options with Travis-CI - we tinkered a little with it and came up with [this blog post](http://blog.biicode.com/automatically-build-publish-via-travis-ci-github/) that automatically publishes as DEV to biicode unless you tag a version in github so it is tagged and released as STABLE in biicode, it has some logic you may not need if you're not thinking on releasing STABLE blocks to biicode.

**Pull request closed without merging**
