### PR TITLE
Array building

### PR DESCRIPTION
**Pull request by dcdillon**
Added functions for building arrays and table_arrays.

### CODE REVIEW

**Comment by dcdillon** [comment]
Sorry....got confused when separating all the pull requests...this one should be clean now.

**Comment by skystrife** [comment]
This looks almost ready. Is it possible to make `push_back()`/`insert()` mirror `table::insert()` after 5c81927 (so we get copy+move for `std::string` for free in one overload), or does that still cause problems?

**Comment by dcdillon** [comment]
I'll look into it.

**Comment by dcdillon** [comment]
Made the changes I think you want.  I also added a `build_toml.cpp` example.  Unfortunately I have no experience at all with `cmake` so I didn't add building for that file to the test.  Perhaps you can either show me how or just do that for me?

**Comment by skystrife** [comment]
Can you give me an example program where the "weird things" happen, along with compiler and/or runtime output so I can replicate and investigate? This should work.

**Comment by dcdillon** [comment]
Indeed...the following code with just the && version of table::insert:

```c++
#include <cpptoml.h>
#include <iostream>

int main(int argc, char *argv[])
{
    cpptoml::table t;
    long i = 1234;
    t.insert("Integer", i);

    std::cout << t << std::endl;
    return 0;
}
```

```
Integer = 

```

Adding the `&` version of the function yields the expected output:
```
Integer = 1234

```

**Comment by dcdillon** [comment]
For what it's worth that's default g++ (4.9.2) on Ubuntu 15.04.  In case the weirdness is limited to my setup here.

**Comment by dcdillon** [comment]
Did a little reading and it would seem that the problem is this:

```c++
template<class T>
void insert(const std::string& key, T&& val)
{
    insert(key, std::make_shared<value<T>>(std::forward<T>(val)));
}
```

Consider when `T = int &`.  Due to the rvalue reference rules you then get:

```c++
void insert(const std::string& key, int& val)
{
    insert(key, std::make_shared<value<int&>>(std::forward<int&>(val)));
}
```

So you actually end up creating a `value<int &>` as opposed to a `value<int>` (which is what you would want).  This is now a `valid_value` due to `std::decay` but it is not in any of our `else if` blocks.

Did you intend for `value<T&>` to be a legal type?  If so we need to add `else/if` handling for this.

**Comment by skystrife** [comment]
Yep. I believe I've fixed this as of 52330f4, can you confirm?

If so, we should make the `push_back()`/`insert()` functions follow that style too.

**Comment by dcdillon** [comment]
I tested it.  Things seem to work properly now.  Committed the changes.  clang-formatted.  I think we're good now.

**Pull request merged**
